### ISSUE TITLE
[review] Uncertainty estimates

### ISSUE THREAD

**Issue by ppxasjsm** [alchemistry/alchemical-best-practices#105]
This one is for @JenkeScheen  and @hannahbrucemacdonald 

In 7.2.5, concerning uncertainty estimates. I found it helpful for many students to realize that free energy error estimates often suffer from exactly the same sampling problems as the free energy estimate itself. Specifically, if the free energy estimate is off because an important region in configuration space has not been sampled, the error estimate has no way to indicate this. The authors might want to make this point super-clear.

**Comment by agrossfield** [comment]
As a non-author, I think this point is incredibly important. More to the point, internal uncertainty estimates are almost guaranteed to *underestimate* the statistical error (relative to repeated runs with distinct starting structures, the gold standard), because they’re based on the assumption that you’ve seen everything.

________________________________
Dr. Alan Grossfield
Dept of Biochemistry and Biophysics
University of Rochester Medical Center
Phone: 585 276 4193
http://membrane.urmc.rochester.edu
https://orcid.org/0000-0002-5877-2789
Pronouns: He/his

**Comment by mrshirts** [comment]
I'm happy to add something on this as well (I will defer to other people to address this first since I have a number of other tasks).

**Comment by davidlmobley** [comment]
Yes, it's important to state very clearly that if you've never seen something, you have NO WAY AT ALL of knowing you have never seen it. (I use a hiking analogy; until you climb to the top of some ridge you have no idea at all about what is in the next valley nor whether it even exists. No amount of information you collect about your initial valley can tell you how many other valleys are adjacent.)

**Comment by hannahbrucemacdonald** [comment]
I've added two sentences, but it felt better putting in Section 8.4 rather than 7.2.5

**Comment by hannahbrucemacdonald** [comment]
Also added something in 7.2.5

**Comment by ppxasjsm** [comment]
Thank you!
