### ISSUE TITLE
[review] conformation v configuration

### ISSUE THREAD

**Issue by ppxasjsm** [alchemistry/alchemical-best-practices#114]
We seem to be using configuration and conformation pretty much interchangeably in the manuscript ( I suspect whoever wrote a section has a favourite term here). Should this be made more uniform? Thoughts anyone?

**Comment by Lnaden** [comment]
I have seen both terms used interchangeably, and I'd bet your suspicion is correct. I would say we should adhere to strict definitions to avoid potential confusion. I propose the following definitions:

* Conformation: Positions and specific geometry of molecular structures, can refer to physical atoms/bonds/angles/etc.
* Configuration: A set of options or choices made by the scientist or software about how a system is setup, run, physical conditions, alchemical paths, etc.

The only place I think it could be confusing is in the overloaded word "configuration" to also mean "set of options" which is why I proposed those definitions. I doubt that confusion would happen in the paper based on the context in which each word appears, but no harm in unifying it.

**Comment by ppxasjsm** [comment]
Interesting. I think it very much depends if you are a statmech person or a chemistry person. Because I would have said that a configuration is the spatial positions and conformation is more broadly a shape. I have never really thought about it though. I think your suggestion makes sense. And yes a configuration is also how you configure your software, but I would have not used it in this context probably. Anyone else got thoughts on this?

**Comment by mrshirts** [comment]
Should we just say they are used interchangeably to refer to the 3D coordinates of the system at given point in time?  I guess the one point of ambiguity is if "conformation" is being used as label for a bunch of 3D coordinates that together represent a metastable state.

**Comment by Lnaden** [comment]
> we just say they are used interchangeably

That might be a better approach. Since this is meant to be a best practices paper, telling readers they could encounter both in the wild would be helpful. I still say we unify it throughout this paper just to unify the language more. 

>  I would have said that a configuration 

I also would say configuration over conformation in my own writing. My definitions above were to minimize any ambiguity independent of reader background.

**Comment by hannahbrucemacdonald** [comment]
Yes, I can’t really put into words what a difference would be. I think what Levi is describing with configuration I would call parameters.

Saying that they are both used interchangeably is probably best seeing as there’s no clarity!

**Comment by ppxasjsm** [comment]
> Yes, I can’t really put into words what a difference would be. I think what Levi is describing with configuration I would call parameters.

I had exactly the same thought, but then thought parametrisation is also not quite right. 
> 
> Saying that they are both used interchangeably is probably best seeing as there’s no clarity!

I may use configuration for when talking about position vectors, but will point out that there is mixed use. 

Thanks for the input!

**Comment by andrrizzi** [comment]
I believe chemists use conformations to mean different geometries with the same topology (so no bond breaking) and configurations instead include all possible geometries of the atoms (including those with different bond topologies). In stat mech the two are often interchangeable because we just integrate over the full Boltzmann distribution determined by a force field potential that doesn't allow bond breaking. I'm not a chemist though so I might be completely wrong.

**Comment by jmichel80** [comment]
Agree with @mrshirts here . Configuration = one microstate defined by position vector (hence configuration integral or configurational integral). Conformation = ambiguous meaning that depends on the context.

**Comment by ppxasjsm** [comment]
I updated the manuscript accordingly.
