### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by yunhuige** [alchemistry/alchemical-best-practices#91]
Hi,

I read the preprint on bioRxiv (https://arxiv.org/abs/2008.03067) and have following suggestions on this version:

1/ It seems Fig 9 and 12 are identical. Based on the captions, I believe Fig 9 is not the supposed figure.

2/ Some figures are far from where they are referred in the text. (e.g., Fig 5-7). I personally feel annoying if I have to scroll up and down multiple times to check figures when I read them in the paper.

3/ Is that possible to talk more about hybrid topology? Or a figure to explain how does that work? I kind of know the answer but just think people may be interested in it. 

4/ Is that possible to include an example of the practical single/dual topology files as part of SI? As a GROMACS user I'm particularly interested in this. Maybe just for a transformation of benzene to benzyl alcohol as illustrated in Fig 3. The detailed parameters may not be necessary but it will be good to show the actual format differences between single and dual topologies. I think it will benefit people (at least GROMACS users) in learning how to perform these simulations in practice. 

I really like this paper as it includes so many detailed explanations and suggestions on this technique. Above are my personal feelings after reading the current version. Some may not be feasible but I hope any of these could contribute to a better version of this paper. 

Thank you!

**Comment by ppxasjsm** [comment]
Hey,

> 1/ It seems Fig 9 and 12 are identical. Based on the captions, I believe Fig 9 is not the supposed figure.

Thanks for the spot. This is due to the way the arxiv submission doesn't allow pdf uploads. I'll fix this on the arxiv.

> 2/ Some figures are far from where they are referred in the text. (e.g., Fig 5-7). I personally feel annoying if I have to scroll up and down multiple times to check figures when I read them in the paper.

I am afraid this cannot easily be fixed due to the fact that the paper is written in LaTeX and has automatic figure placement. I can try and improve this with proofs for a published version. 

>3/ Is that possible to talk more about hybrid topology? Or a figure to explain how does that work? I kind of know the answer but just think people may be interested in it.

Yes! Ideally if you have a pragraph you would like to add please suggest it and a place in the document where it can go and I'll happily add it. 

>4/ Is that possible to include an example of the practical single/dual topology files as part of SI? As a GROMACS user I'm particularly interested in this. Maybe just for a transformation of benzene to benzyl alcohol as illustrated in Fig 3. The detailed parameters may not be necessary but it will be good to show the actual format differences between single and dual topologies. I think it will benefit people (at least GROMACS users) in learning how to perform these simulations in practice.

I like this suggestion. At the moment we don't really have a SI and the paper itself is already a monster. I'll add it to a list of ideal future improvements, but probably wont' fix it immediately. 

>I really like this paper as it includes so many detailed explanations and suggestions on this technique. Above are my personal feelings after reading the current version. Some may not be feasible but I hope any of these could contribute to a better version of this paper.

Thank you for all your feedback! Much appreciated.

**Comment by ppxasjsm** [comment]
I will add you to the acknowledgements. Is it ok for you to appear as Yunhui Ge?

**Comment by yunhuige** [comment]
I talked to Dr. Mobley and I will prepare a draft talking about the hybrid topology idea (and figures if necessary). Then I will pass it to Dr. Mobley for edits. Sound good? @ppxasjsm

**Comment by ppxasjsm** [comment]
Yes sounds great! Thanks for this.

**Comment by ppxasjsm** [comment]
@yunhuige, how are you getting on with this? We've had revisions back for version 1.0 and it would be great to also incorporate your edits.

**Comment by yunhuige** [comment]
@ppxasjsm I prepared my draft and have sent it to Dr. Mobley. I will ask him for any updates today.

**Comment by ppxasjsm** [comment]
Great! Thank you.

**Comment by davidlmobley** [comment]
We've actually realized that this is super confusing in the literature, and there may not be a "correct" terminology, which has slowed me down on this point. I'll put it into the queue with the other issues you've assigned me.

**Comment by davidlmobley** [comment]
OK, so @yunhuige and I discussed the issue of single/hybrid/dual/separated topologies some more and I dug in to the literature a bit and have revised the relevant section (7.1.1) to clarify/make it more correct (for now on Overleaf). I think mainly we were using a term "hybrid" that I've not seen used except for by Gapsys, de Groot etc., to refer to something I called "separated topologies". So I've added some text clarifying what "hybrid" means very briefly, then clarified/mentioned "separated topologies" and otherwise tried to clarify that section.

@ppxasjsm do you want to save item (4) in a separate issue and we can close this one?

**Comment by ppxasjsm** [comment]
Yes that would be great thanks!
