### ISSUE TITLE
[review] Fig 1 inconsistency

### ISSUE THREAD

**Issue by ppxasjsm** [alchemistry/alchemical-best-practices#93]
Figure 1: For me there is no intrinsic difference between the free energy calculations shown in panel D and F, both transformations should be performed in the bound and unbound states to obtain meaningful results, and both should be termed relative calculations (ΔΔG). Maybe it could be more clearly indicated in general if a whole molecule is decoupled and if only a part of a molecule is transformed?

**Comment by JenkeScheen** [comment]
I could 
- change ΔG to ΔΔG for all rows
- swap E and F so that it's easier to compare the 'effect of mutations' with the 'relative FE of binding' row
- include an 'interaction' schematic to D to emphasise that the interaction with the ligand is affected by the mutation, such as here:
![image](https://user-images.githubusercontent.com/43140137/94557615-b611e080-0256-11eb-8ad5-c804587939cc.png)
    
let me know which you want me to implement, if at all.

**Comment by ppxasjsm** [comment]
I like all of these suggestions! Please go ahead with them!

**Comment by ppxasjsm** [comment]
Thank you for the figure changes.
