### ISSUE TITLE
[review] Section 7

### ISSUE THREAD

**Issue by ppxasjsm** [alchemistry/alchemical-best-practices#96]
Any thoughts on this comments?

Section 7.2.1: Using a flat-bottom restraining potential in which the ligand never hits the potential wall is similar to using no restraining potential at all. I would not suggest skipping a reweighting step; if the energetic contribution of the restraint is little, the reweighting will not introduce much noise and is technically easy to perform.
Section 7.2.5 and Figure 9: The concept of evaluating both forward and reverse cumulative averages is nicely described in reference 42. I would cite the reference in this section.

**Comment by jmichel80** [comment]
The ms states 

''Alternatively, a flat-bottom restraint can be activated also in the decoupled state as long as the second restraint (e.g., a harmonic or Boresch restraint) prevents the ligand to hit the wall of the flat-bottom potential [73].''

Not sure where the second restraint part bits come from.  This is not how we run ABFE with flat-bottom restraints. We use a  series of flat-bottom distance restraints only. The decoupled state feels the walls. 

If the restraint is never hit the free energy change from the reweigthing step is (numerically) zero.

**Comment by davidlmobley** [comment]
I don't have any insights on this, but I think @andrrizzi might.

**Comment by andrrizzi** [comment]
> Section 7.2.1: Using a flat-bottom restraining potential in which the ligand never hits the potential wall is similar to using no restraining potential at all. I would not suggest skipping a reweighting step; if the energetic contribution of the restraint is little, the reweighting will not introduce much noise and is technically easy to perform.

I've slightly changed the wording to clarify this point. The reweighting can be skipped if the ligand is never _sampled_ while hitting the wall because, as @jmichel80 says, the numerical correction would be exactly zero. Using the restraint is different from using no restraining potential at all because during the MD simulation the ligand might still very occasionally hit the wall (thus limiting its volume to the binding site) even if we never observe it after subsampling the trajectory.

> Section 7.2.5 and Figure 9: The concept of evaluating both forward and reverse cumulative averages is nicely described in reference 42. I would cite the reference in this section.

I added the citation to that paragraph.

> Not sure where the second restraint part bits come from. This is not how we run ABFE with flat-bottom restraints. We use a series of flat-bottom distance restraints only. The decoupled state feels the walls.

I think this is the approach used, for example, by @mrshirts in their SAMPL6 submission: A "loose" flat-bottom to make sure the ligand stays in the binding site in the bound state, and a tight harmonic restraint to restrict the noninteracting ligand. That paragraph is pointing out that when multiple restraints affect the ligand in the non-interacting state, the standard anlytical corrections do not generally apply. I have rewritten that couple of sentences to make this clearer. Feel free to adjust/remove.

**Comment by ppxasjsm** [comment]
Looks good! Thank you
